<?php
/**
 * Created by PhpStorm.
 * User: HVSoftware
 * Date: 2-9-2019
 * Time: 19:50
 */

namespace BigRegister;

/**
 * Class BigSearchTest
 */
class BigSearchTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var BigSearch
     */
    private $search;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->search = new BigSearch();
    }

    public function testSearchByRegistration()
    {
        $this->assertNotNull($this->search);
    }

    public function testSearchByCriteria()
    {
        $this->assertNotNull($this->search);
    }
}
